version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
    ignore:
      - dependency-name: "golangci/golangci-lint-action"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-deps:
        patterns: ["*"]
